### ISSUE TITLE
GA events are fired twice in BackOffice

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/ps_googleanalytics#61] opened 2020-08-17 08:48 UTC
THe GA JS code is persent also in the backoffice.

PS 1.7.6.7
GA 4.0.0

GA JS code must be fired only in frontoffice.

**Comment by matks** [comment] 2020-08-17 08:54
This is not a bug, it's a feature.

See the README:

> Google Tag Assistant will report "No HTTP Response detected" error in Prestashop back-office. This is not a bug. This happens, because the module does not send page views in BO, not to influence statistics. Only events, like refunds, are sent from BO.

**Comment by HartLarsson** [comment] 2020-08-17 09:56
strange feature because in Analytics i can see my backoffice pages!
![image](https://user-images.githubusercontent.com/16102074/90383543-947ee000-e080-11ea-943d-d902ea86b285.png)

I hope this feature, that for me is a bug (tracking BO pages) must be removed, also because is fired TWICE!

**Comment by matks** [comment] 2020-08-17 10:03
> strange feature because in Analytics i can see my backoffice pages!

There might be weird behaviors, bugs or issues in how the feature is implemented :)

> I hope this feature, that for me is a bug (tracking BO pages) must be removed

No it will not be removed :) . Some people use this feature. If you do not like it you can modify the module to disable it in the back-office.

This module is free. It should provide as much as possible features for users, so that everybody can use what they want. Of course if you dont want to use some of its features, since it's open-source you can customize it to fit your needs 😄

**Comment by HartLarsson** [comment] 2020-08-17 10:04
"No it will not be removed :) . Some people use this feature. If you do not like it you can modify the module to disable it in the back-office."
an you lease tell me how to remove the BO tracking or to fix the tracking of all BO pages?

**Comment by HartLarsson** [comment] 2020-08-17 10:07
> There might be weird behaviors, bugs or issues in how the feature is implemented :)

for sure there is something that not work, because is ok tracking refunds but not all pages :)

**Comment by HartLarsson** [comment] 2020-08-17 10:15
seems that in the ps_googleanalytics.tpl this part of the code is always FALSE

`    {if $backOffice}
        ga('set', 'nonInteraction', true);
    {else}
        ga('send', 'pageview');
    {/if}`

is why a pageview is always fired in BO while in previous 3,2.0 was working correctly

**Comment by Hlavtox** [comment] 2020-08-27 12:13
@matks it's a bug, it cannot track BO pages, it does so after refactoring

**Comment by matks** [comment] 2020-08-27 13:03
@HartLarsson I have modified this issue title to "GA events are fired twice" as this is the real bug for me.

If you think it makes sense, you can open an issue "We should be able to disable Back-Office tracking".

**Comment by matks** [comment] 2020-08-27 14:29
@HartLarsson Well I made it myself in the end 😄  https://github.com/PrestaShop/ps_googleanalytics/issues/71

**Comment by HartLarsson** [comment] 2020-08-28 16:54
> @HartLarsson I have modified this issue title to "GA events are fired twice" as this is the real bug for me.
> 
> If you think it makes sense, you can open an issue "We should be able to disable Back-Office tracking".

well don't know if are sent twice but for sure are sent in page where there is not any importance to tracking it like:

Edit a product in Backoffice or watch some configuration pages.

The module must be redone with the only tracking of particular BO operation: order cancelled or refund for example.

Because these kind of info are interested only if is enabled on analytics the ecommerce conversion, i think normally the module must track only the FO operations especially the checkout steps that now are not tracked like on 1.6

**Comment by Hlavtox** [comment] 2020-12-17 13:46
@matks @HartLarsson Fixed by https://github.com/PrestaShop/ps_googleanalytics/pull/77

**Comment by jeremLF** [comment] 2021-02-23 14:43
> can you please tell me how to remove the BO tracking or to fix the tracking of all BO pages?

I may be late but I think you have to unlink the module from the displayBackOfficeHeader position.

**Comment by matks** [comment] 2021-07-28 15:31
Fix finally available in new module version https://github.com/PrestaShop/ps_googleanalytics/releases/tag/v4.1.0

**Closed by matks** 2021-07-28 15:31 UTC
Labels: bug
