### ISSUE TITLE
ps_googleanalytics - Not tracking pageviews on ps 1.7.4.4

### ISSUE THREAD

**Issue by geimsdin** [PrestaShop/ps_googleanalytics#30] opened 2019-02-01 12:34 UTC
The snippet code is missing a part, it doesn't track pageviews. I added 

ga('send', 'pageview');

At the end of the script and now is working again. I don't know if it is the correct solution.

**Comment by masiorama** [comment] 2019-02-07 13:41
I had the same problem #29 .
Just uninstall and reinstall and it should fix it.

**Comment by destrosvet** [comment] 2019-04-08 19:02
I have same problem - uninstall and reinstall doesn't help me. ga('send', 'pageview') missing but other events like ga("send", "event", "UX", "detail", "Product Detail View", {nonInteraction: 1}) working..
PS 1.7.5.0

**Comment by daniele-webmaori** [comment] 2019-04-10 12:53
same

**Comment by mir69** [comment] 2019-06-26 01:54
I have the same problem, module 3.1.3.
This is my code in pages:
<script type="text/javascript">
	(window.gaDevIds=window.gaDevIds||[]).push('d6YPbH');
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-XXXXX407-2', 'auto');
                
    ga('require', 'ec');
</script>

Missing as well the "ga('send', 'pageview');"
Can anybody please tell us, where to add this in module?
Thank you very much!

**Comment by LanderU** [comment] 2019-07-10 07:27
I'm facing the same problem. Any updates on how to fix it?

**Comment by mir69** [comment] 2019-07-10 08:40
Seems like NOBODY CARES. I think the Presta team is developing the version 1.8. I wish the just quite the developing new stuff for two years, and make the last version JUST WORKING PROPERLY...

**Comment by soulraven** [comment] 2019-11-25 15:25
same here,
after days of debugging , after i added: ga('send', 'pageview');
just stared to work.

**Comment by mir69** [comment] 2019-11-25 16:09
Hi soulraven, can you please cope here the whole php code? Thank you.

**Comment by soulraven** [comment] 2019-11-25 16:56
hi,
the problem is not on PHP side, is on template side,
`{literal}
<script async type="text/javascript">
    (window.gaDevIds=window.gaDevIds||[]).push('d6YPbH');
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

{/literal}
    {if $gaCrossdomainEnabled}
        ga('create', '{$gaAccountId|escape:'htmlall':'UTF-8'}', 'auto', {literal}{'allowLinker': true}{/literal});
        ga('require', 'linker');
        ga('linker:autoLink', [
        {foreach from=$shops item=shop}
            {if $shop.id_shop != $currentShopId}
            {if $useSecureMode}'{$shop.domain_ssl|escape:'htmlall':'UTF-8'}'{else}'{$shop.domain|escape:'htmlall':'UTF-8'}'{/if},
            {/if}
        {/foreach}
        ]);
    {else}
        
        ga('create', '{$gaAccountId|escape:'htmlall':'UTF-8'}', 'auto');
    {/if}
    {if $userId && !$backOffice}
        ga('set', 'userId', '{$userId|escape:'htmlall':'UTF-8'}');
    {/if}
    {if $gaAnonymizeEnabled}
        ga('set', 'anonymizeIp', true);
    {/if}
    {if $backOffice}
        ga('set', 'nonInteraction', true);
    {/if}
{literal}
    ga('require', 'ec');
    ga('send', 'pageview'); ->added by me
</script>
{/literal}`

**Comment by mir69** [comment] 2019-11-25 17:09
Thank you! Will move back home from office and test it!

**Comment by matks** [comment] 2020-08-27 13:33
It seems issue is fixed in v4.0.0. Feel free to reopen an issue if you find usecase where issue is still observable.

**Closed by matks** 2020-08-27 13:33 UTC
